
INSERT INTO `Projects_Employees` (`EId`,`PId`)
VALUES
  (28,26),
  (6,1),
  (22,8),
  (30,14),
  (17,3),
  (5,28),
  (6,11),
  (25,8),
  (2,3),
  (9,10);
INSERT INTO `Projects_Employees` (`EId`,`PId`)
VALUES
  (6,21),
  (23,15),
  (3,2),
  (17,11),
  (11,5),
  (7,25),
  (3,26),
  (26,28),
  (19,24),
  (19,27);
INSERT INTO `Projects_Employees` (`EId`,`PId`)
VALUES
  (15,11),
  (5,20),
  (21,17),
  (25,23),
  (8,5),
  (29,27),
  (10,19),
  (10,7),
  (6,18),
  (13,12);
